"use client"

import { Provider } from "react-redux";
import {persistor,store} from '../app/redux/store'
import { PersistGate } from "redux-persist/integration/react";

// Import necessary modules and components
import  SessionProvider  from "./SessionProvider"; // Import SessionProvider from next-auth/react for session management
import Footer from "./components/footer/Footer"; // Import the Footer component
import Navbar from "./components/navbar/Navbar"; // Import the Navbar component
import FreeDelivery from "./components/freeDelivery/FreeDelivery";
import "./globals.css"; // Import global CSS styles
import { Inter } from "next/font/google"; // Import the Inter font from Google Fonts

// Initialize the Inter font with the 'latin' subset
const inter = Inter({ subsets: ["latin"] });

// Define metadata for the application
const metadata = {
  title: "My e-book store",
  description: "Generated by @mit",
};

// Define the RootLayout component
export default function RootLayout({ children }) {
  return (
    // Define the HTML structure with language set to 'en'
    <html lang="en">
      {/* Define the body of the HTML document */}
      <body className={inter.className}>
      <Provider store={store}>
          <PersistGate persistor={persistor}>
            <SessionProvider>
              <FreeDelivery />
              <Navbar />
              {children}
              <Footer />
            </SessionProvider>
          </PersistGate>
        </Provider>
        
      </body>
    </html>
  );
}
